/* tslint:disable */
/* eslint-disable */

/* auto-generated by napi-rs on build; kept here in source so that
   TypeScript can resolve types before the first native build. */

export const enum Availability {
  Available = 'Available',
  NoHardware = 'NoHardware',
  NotEnrolledOs = 'NotEnrolledOs',
  Unsupported = 'Unsupported'
}

export const enum ErrorKind {
  Cancelled = 'Cancelled',
  LockedOut = 'LockedOut',
  Invalidated = 'Invalidated',
  NotAvailable = 'NotAvailable',
  OsError = 'OsError'
}

export function available(): Promise<Availability>
export function hasEnrollment(userId: string): Promise<boolean>
export function enroll(userId: string, credentials: Buffer): Promise<Buffer>
export function unenroll(userId: string): Promise<void>
export function unlock(userId: string, wrapped: Buffer): Promise<Buffer>

/** True iff the native binary failed to load. JS-only stub mode. */
export const __notBuilt: boolean | undefined
